apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: openemr-certs
  labels:
    io.kompose.service: openemr
  name: openemr
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8443"
    port: 8443
    targetPort: 8443
  selector:
    io.kompose.service: openemr
